window.LinkFuelData = {
  summary: {
    totalSites: 428,
    activePublishers: 92,
    avgTurnaroundDays: 4.1,
    buyerWalletBalance: 12840,
  },
  project: {
    name: "Velora Exchange",
    domain: "velora.trade",
    vertical: "Crypto / Web3",
    targetCountries: ["US", "UK", "AE"],
    targetLanguages: ["English"],
    budgetRange: "$3k - $8k",
    objective: "Authority growth with finance-relevant placements",
    notes: "Prefer sites that accept exchange, wallet and DeFi content. Avoid weak general blogs.",
  },
  offers: [
    {
      id: "offer-001",
      siteName: "BlockDepth Journal",
      domain: "blockdepthjournal.com",
      country: "US",
      language: "English",
      verticals: ["Crypto / Web3", "Fintech / Payment"],
      dr: 71,
      traffic: 48200,
      turnaroundDays: 3,
      price: 420,
      offerType: "Guest Post",
      moneyPageAllowed: true,
      sponsoredRequired: false,
      contentWriting: true,
      score: 94,
      reasons: [
        "Strong vertical match for crypto exchange content",
        "US audience and editorial tone fit your target market",
        "Accepts commercial landing pages and anchor flexibility",
      ],
      risks: ["Finance claims still require publisher review"],
      description: "A crypto-finance publication with active editorial review and strong US traffic.",
    },
    {
      id: "offer-002",
      siteName: "Finroute Daily",
      domain: "finroutedaily.com",
      country: "UK",
      language: "English",
      verticals: ["Fintech / Payment", "Crypto / Web3"],
      dr: 67,
      traffic: 32100,
      turnaroundDays: 5,
      price: 350,
      offerType: "Link Insertion",
      moneyPageAllowed: true,
      sponsoredRequired: true,
      contentWriting: false,
      score: 88,
      reasons: [
        "Budget-friendly fit inside your current wallet plan",
        "Supports finance and payment adjacent topics",
        "Good option for lower friction branded anchors",
      ],
      risks: ["Sponsored label required"],
      description: "A fintech-heavy blog that accepts commercial updates and curated niche edits.",
    },
    {
      id: "offer-003",
      siteName: "Macro Ledger",
      domain: "macroledger.co",
      country: "AE",
      language: "English",
      verticals: ["Crypto / Web3", "Forex"],
      dr: 63,
      traffic: 21400,
      turnaroundDays: 4,
      price: 290,
      offerType: "Guest Post",
      moneyPageAllowed: false,
      sponsoredRequired: false,
      contentWriting: true,
      score: 82,
      reasons: [
        "Regional fit for UAE growth goals",
        "Fast turnaround for campaign pacing",
        "Editorial style works for educational crypto narratives",
      ],
      risks: ["Direct exchange signup pages are not accepted"],
      description: "Regional finance publication suited for thought leadership and top-of-funnel crypto content.",
    },
    {
      id: "offer-004",
      siteName: "Payment Rail Report",
      domain: "paymentrailreport.com",
      country: "US",
      language: "English",
      verticals: ["Fintech / Payment"],
      dr: 75,
      traffic: 54100,
      turnaroundDays: 7,
      price: 560,
      offerType: "Guest Post",
      moneyPageAllowed: true,
      sponsoredRequired: true,
      contentWriting: true,
      score: 76,
      reasons: [
        "Excellent authority for finance adjacency",
        "Useful if you expand into payment narrative angles",
      ],
      risks: ["Less direct vertical fit than crypto-native media", "Higher price"],
      description: "High-authority payment publication with strong editorial standards and enterprise readership.",
    },
    {
      id: "offer-005",
      siteName: "FX Operator",
      domain: "fxoperator.net",
      country: "UK",
      language: "English",
      verticals: ["Forex"],
      dr: 58,
      traffic: 19800,
      turnaroundDays: 2,
      price: 210,
      offerType: "Link Insertion",
      moneyPageAllowed: true,
      sponsoredRequired: false,
      contentWriting: false,
      score: 61,
      reasons: [
        "Very fast turnaround",
        "Low-cost test option if you branch into trading content",
      ],
      risks: ["Weak topical match for exchange-first positioning"],
      description: "A trading-focused site suited for forex and broker-related angles.",
    },
  ],
  orders: [
    {
      id: "LF-240321",
      siteName: "BlockDepth Journal",
      offerType: "Guest Post",
      amount: 420,
      status: "In Progress",
      dueDate: "2026-04-25",
      brief: "Feature Velora's on-chain execution layer with brand anchor.",
    },
    {
      id: "LF-240298",
      siteName: "Finroute Daily",
      offerType: "Link Insertion",
      amount: 350,
      status: "Awaiting Buyer Reply",
      dueDate: "2026-04-23",
      brief: "Need final target URL confirmation for UK landing page.",
    },
    {
      id: "LF-240255",
      siteName: "Macro Ledger",
      offerType: "Guest Post",
      amount: 290,
      status: "Completed",
      dueDate: "2026-04-18",
      brief: "Published as an educational feature around DeFi trading infrastructure.",
    },
  ],
  walletTransactions: [
    { date: "2026-04-20", type: "Deposit", amount: "+5000 USDT", status: "Paid" },
    { date: "2026-04-21", type: "Order Payment", amount: "-420 USD", status: "Settled" },
    { date: "2026-04-21", type: "Order Payment", amount: "-350 USD", status: "Settled" },
    { date: "2026-04-22", type: "Refund to Wallet", amount: "+90 USD", status: "Pending Review" },
  ],
  publisherSites: [
    {
      name: "BlockDepth Journal",
      domain: "blockdepthjournal.com",
      status: "Approved",
      verticals: "Crypto, Fintech",
      offers: "Guest Post, Writing",
      payout: "$3,420 MTD",
    },
    {
      name: "Macro Ledger",
      domain: "macroledger.co",
      status: "Pending QA",
      verticals: "Crypto, Forex",
      offers: "Guest Post",
      payout: "$1,180 MTD",
    },
  ],
  adminQueue: [
    {
      type: "Site Review",
      target: "chainalpha.news",
      reason: "Claims crypto + loan acceptance, needs manual policy review",
      priority: "High",
    },
    {
      type: "Order Dispute",
      target: "LF-240298",
      reason: "Buyer wants homepage URL, publisher forbids homepage links",
      priority: "Medium",
    },
    {
      type: "Deposit Check",
      target: "CR-778210",
      reason: "Webhook delayed, payment hash submitted manually by buyer",
      priority: "Medium",
    },
  ],
};
